Expand Xwayland screen size
wayland-transpositor/wprs pull request #29
Opened 2024-05-02 19:45 UTC by maxhbooth

Right now there isn't a way to handle events wayland events that
move beyond the bounds of the xwayland screen.  E.g. mouse events
outside the bounds of the wayland surface will hit the screen bounds
when passed to x11.  So let's make the xwayland screen bigger
so that we have some buffer to work with.

2024-05-03 15:59 UTC, nicolasavru requested changes

2024-05-03 15:59 UTC, nicolasavru commented on src/xwayland_xdg_shell/compositor.rs
> +    // we are lying to xwayland about the size of the display and offsetting all our x11 windows
nit: start the first sentence with a capital, like the others. And single spaces between sentences.

2024-05-03 15:59 UTC, nicolasavru commented on src/xwayland_xdg_shell/compositor.rs
> +    expanded_dimensions.w *= 3;
Why not just do 32k x 32k?

2024-05-03 15:59 UTC, nicolasavru commented on src/xwayland_xdg_shell/mod.rs
> -            // last_focused_window holds a handle to the window, not just an id, so
Why don't we need this anymore?

2024-05-03 17:11 UTC, nicolasavru commented on src/xwayland_xdg_shell/mod.rs
> -            // last_focused_window holds a handle to the window, not just an id, so
Right, this only applies to for_toplevel, which you're removing.

2024-05-03 17:19 UTC, maxhbooth commented on src/xwayland_xdg_shell/compositor.rs
> +    expanded_dimensions.w *= 3;
I mostly just wasn't sure what a good size would actually be.  I'll just change this to 32k x 32k then (also open to bikeshedding on what the best size would be though.)

2024-05-03 17:31 UTC, maxhbooth commented on src/xwayland_xdg_shell/compositor.rs
> +    expanded_dimensions.w *= 3;
nvm something crashed when I did 32k x 32k.  I'm doing 16kx 16k.

2024-05-03 17:36 UTC, nicolasavru approved these changes

2024-05-03 17:45 UTC, merged

2025-07-24 17:11 UTC, corngood commented
I found that when running `xfreerdp`, it will default to an extremely large window size since it's trying to fill the screen.  In master this is currently 3x the screen size (due to #48).

xrandr will report 3x the screen size as well, while wayland-info is accurate.

I'm not sure if this is worth opening an issue for, because it seems like a natural consequence of this workaround.

2025-07-24 19:20 UTC, maxhbooth commented
@corngood we could certainly consider a FR to let users choose between a 1:1 screen size or 3:1 screen size depending on what they're doing, if you'd like to open an issue for that?  But yeah the problem boils down to that with a 1:1 screen size then xwayland won't have the coordinate space to place windows outside the apps borders.  Which UX is worse is probably app dependent.